#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : logrotate
Version  : 3.14.0
Release  : 1
URL      : https://github.com/logrotate/logrotate/releases/download/3.14.0/logrotate-3.14.0.tar.xz
Source0  : https://github.com/logrotate/logrotate/releases/download/3.14.0/logrotate-3.14.0.tar.xz
Summary  : Rotates, compresses, removes and mails system log files
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: logrotate-bin
Requires: logrotate-license
Requires: logrotate-man
BuildRequires : acl-dev
BuildRequires : popt-dev

%description
The logrotate utility is designed to simplify the administration of
log files on a system which generates a lot of log files.  Logrotate
allows for the automatic rotation compression, removal and mailing of
log files.  Logrotate can be set to handle a log file daily, weekly,
monthly or when the log file gets to a certain size.  Normally,
logrotate runs as a daily cron job.

Install the logrotate package if you need a utility to deal with the
log files on your system.

%package bin
Summary: bin components for the logrotate package.
Group: Binaries
Requires: logrotate-license
Requires: logrotate-man

%description bin
bin components for the logrotate package.


%package license
Summary: license components for the logrotate package.
Group: Default

%description license
license components for the logrotate package.


%package man
Summary: man components for the logrotate package.
Group: Default

%description man
man components for the logrotate package.


%prep
%setup -q -n logrotate-3.14.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534186713
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534186713
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/logrotate
cp COPYING %{buildroot}/usr/share/doc/logrotate/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/logrotate

%files license
%defattr(-,root,root,-)
/usr/share/doc/logrotate/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man5/logrotate.conf.5
/usr/share/man/man8/logrotate.8
